# Generated by Django 2.0.5 on 2018-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='city',
            field=models.CharField(default='Raipur', max_length=250),
        ),
        migrations.AddField(
            model_name='myusers',
            name='dob',
            field=models.CharField(default='02,Apr 1996', max_length=50),
        ),
        migrations.AddField(
            model_name='myusers',
            name='gender',
            field=models.CharField(default='Male', max_length=250),
        ),
        migrations.AddField(
            model_name='myusers',
            name='pic',
            field=models.CharField(default='pic1.png', max_length=50),
        ),
    ]
