# Generated by Django 2.0.5 on 2018-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180606_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='pic',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
