# Generated by Django 2.0.5 on 2018-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20180607_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
